# Makefile For X86 Architecture Related Component

# This File Describe Some Rules For Building X86 Architecture Depedent Component

SCRIPT_PATH	:=	../script

-include $(SCRIPT_PATH)/func.mk

.DEFAULT_GOAL 	:=	main


.PHONY: main
main:
