
# This Makefile Control All of the project

# Copyright : @QIUYIXIANG
# Create on : 2023-07-23

# Include Rules Makefile
-include $(CURDIR)/Rules.mk


# Define All Depedencies 
# DEPENDENCIES	:=	


### Main Target
# Main Target for building this whole project !
.DEFAULT_GOAL	:=	all

.PHONY: all
all:
	@$(call _path_check)

# Clean All the Build Target
.PHONY: clean
clean:
	rm -rf $(GLOBAL_BUILD)